from django.forms import ModelForm
from .models import transplant_model, death_model

class transplant_form(ModelForm):
    class Meta:
        model = transplant_model
        fields = [
            'Age',
            'Gender',
            'Weight',
            'BMI',
            'Systolic_Pressure',
            'Diastolic_Pressure',
            'Total_Cholesterol',
            'HDL',
            'LDL',
            'Total_Cholesterol_HDL',
            'Triglycerides',
            'Platelets',
            'Lymphocytes',
            'Neutrophils',
            'Monocytes',
            'Eosinophils',
            'Basophils',
            'Glycemia',
            'Total_Bilirubin',
            'Albumin',
            'Creatinine',
            'Natremia',
            'INR',
            'Smoking',
            'Diabetes_PreTx',
            'HyperTension',
            'Functional_Study_of_Positive_Ischemia',
            'Hepatocellular_Carcinoma',
            'Aspirin',
            'Statins',
            'Prednisone',
            'Tacrolimus',
            'Ciclosoporine',
            'Azathioprine',
            'Contraindication_for_TH',
            'Entry_List',
            'MELD_Score',
            'Framingham_CV_Risk',
            'Vascular_Age',
            'Vascular_Age_Biological_Age'
        ]
        help_texts = {'Gender':"mm"}

class death_form(ModelForm):
    class Meta:
        model = death_model
        fields = [
            'Age',
            'Gender',
            'Weight',
            'BMI',
            'Systolic_Pressure',
            'Diastolic_Pressure',
            'Total_Cholesterol',
            'HDL',
            'LDL',
            'Total_Cholesterol_HDL',
            'Triglycerides',
            'Platelets',
            'Lymphocytes',
            'Neutrophils',
            'Monocytes',
            'Eosinophils',
            'Basophils',
            'Glycemia',
            'Total_Bilirubin',
            'Albumin',
            'Creatinine',
            'Natremia',
            'INR',
            'Smoking',
            'Diabetes_PreTx',
            'HyperTension',
            'Functional_Study_of_Positive_Ischemia',
            'Hepatocellular_Carcinoma',
            'Aspirin',
            'Statins',
            'Prednisone',
            'Tacrolimus',
            'Ciclosoporine',
            'Azathioprine',
            'Contraindication_for_TH',
            'Entry_List',
            'MELD_Score',
            'Framingham_CV_Risk',
            'Vascular_Age',
            'Vascular_Age_Biological_Age'

        ]
