from django.db import models
from django.contrib import admin

class transplant_model(models.Model):
    Gender = models.FloatField(default=0)
    Age = models.FloatField(default=0)
    Weight = models.FloatField(default=0)
    BMI = models.FloatField(default=0)
    Systolic_Pressure = models.FloatField(default=0)
    Diastolic_Pressure = models.FloatField(default=0)
    Total_Cholesterol = models.FloatField(default=0)
    HDL = models.FloatField(default=0)
    LDL = models.FloatField(default=0)
    Total_Cholesterol_HDL = models.FloatField(default=0)
    Triglycerides = models.FloatField(default=0)
    Platelets = models.FloatField(default=0)
    Lymphocytes = models.FloatField(default=0)
    Neutrophils = models.FloatField(default=0)
    Monocytes = models.FloatField(default=0)
    Eosinophils = models.FloatField(default=0)
    Basophils = models.FloatField(default=0)
    Glycemia = models.FloatField(default=0)
    Total_Bilirubin = models.FloatField(default=0)
    Albumin = models.FloatField(default=0)
    Creatinine = models.FloatField(default=0)
    Natremia = models.FloatField(default=0)
    INR = models.FloatField(default=0)
    Smoking = models.FloatField(default=0)
    Diabetes_PreTx = models.FloatField(default=0)
    HyperTension = models.FloatField(default=0)
    Functional_Study_of_Positive_Ischemia = models.FloatField(default=0)
    Hepatocellular_Carcinoma = models.FloatField(default=0)
    Aspirin = models.FloatField(default=0)
    Statins = models.FloatField(default=0)
    Prednisone = models.FloatField(default=0)
    Tacrolimus = models.FloatField(default=0)
    Ciclosoporine = models.FloatField(default=0)
    Azathioprine = models.FloatField(default=0)
    Contraindication_for_TH = models.FloatField(default=0)
    Entry_List = models.FloatField(default=0)
    MELD_Score = models.FloatField(default=0)
    Framingham_CV_Risk = models.FloatField(default=0)
    Vascular_Age = models.FloatField(default=0)
    Vascular_Age_Biological_Age = models.FloatField(default=0)

admin.site.register(transplant_model)

class death_model(models.Model):
    Gender = models.FloatField(default=0)
    Age = models.FloatField(default=0)
    Weight = models.FloatField(default=0)
    BMI = models.FloatField(default=0)
    Systolic_Pressure = models.FloatField(default=0)
    Diastolic_Pressure = models.FloatField(default=0)
    Total_Cholesterol = models.FloatField(default=0)
    HDL = models.FloatField(default=0)
    LDL = models.FloatField(default=0)
    Total_Cholesterol_HDL = models.FloatField(default=0)
    Triglycerides = models.FloatField(default=0)
    Platelets = models.FloatField(default=0)
    Lymphocytes = models.FloatField(default=0)
    Neutrophils = models.FloatField(default=0)
    Monocytes = models.FloatField(default=0)
    Eosinophils = models.FloatField(default=0)
    Basophils = models.FloatField(default=0)
    Glycemia = models.FloatField(default=0)
    Total_Bilirubin = models.FloatField(default=0)
    Albumin = models.FloatField(default=0)
    Creatinine = models.FloatField(default=0)
    Natremia = models.FloatField(default=0)
    INR = models.FloatField(default=0)
    Smoking = models.FloatField(default=0)
    Diabetes_PreTx = models.FloatField(default=0)
    HyperTension = models.FloatField(default=0)
    Functional_Study_of_Positive_Ischemia = models.FloatField(default=0)
    Hepatocellular_Carcinoma = models.FloatField(default=0)
    Aspirin = models.FloatField(default=0)
    Statins = models.FloatField(default=0)
    Prednisone = models.FloatField(default=0)
    Tacrolimus = models.FloatField(default=0)
    Ciclosoporine = models.FloatField(default=0)
    Azathioprine = models.FloatField(default=0)
    Contraindication_for_TH = models.FloatField(default=0)
    Entry_List = models.FloatField(default=0)
    MELD_Score = models.FloatField(default=0)
    Framingham_CV_Risk = models.FloatField(default=0)
    Vascular_Age = models.FloatField(default=0)
    Vascular_Age_Biological_Age = models.FloatField(default=0)

admin.site.register(death_model)
